name: Update Blocklist

on:
  repository_dispatch:
    types: [update-blocklist]

jobs:
  update_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update block.txt
        run: |
          NEW_IP="${{ github.event.client_payload.new_ip }}"
          if ! grep -Fxq "$NEW_IP" block.txt; then
            echo "$NEW_IP" >> block.txt
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            git add block.txt
            git commit -m "Add new blocked IP: $NEW_IP"
            git push origin main
          fi
